### ISSUE TITLE
To-Do list

### ISSUE THREAD

**Issue by afranques** [afranques44/quovis#1]
- [x] skip button in take picture step
- [x] button add categories gets hidden
- [x] work with the margins so that the shadows at the top/bottom don't look cut
- [ ] edit locations
- [ ] ask for confirmation when delete location
- [ ] don't save the picture on general gallery
- [ ] let user move the map to any other location
- [ ] show city name in location description
- [ ] organize locations by countries/cities
- [ ] better color layout for the tabs
- [ ] export locations
- [ ] import locations
- [ ] change database from sqlite to realm
- [ ] compatibility between android versions
- [ ] fix crash when app wakes up
- [ ] save locations online
- [ ] save pictures online
- [ ] comment all the code and check private/public/static/final proper use
